# Generated by Django 4.0.4 on 2022-05-01 06:16

from django.db import migrations, models
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='notice',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=notice.models.get_file_path, verbose_name='파일'),
        ),
        migrations.AddField(
            model_name='notice',
            name='upload_images',
            field=models.FileField(blank=True, null=True, upload_to=notice.models.get_file_path, verbose_name='이미지파일'),
        ),
    ]
